app_flask/project/__init__.py
from flask import Flask

from .views import (main_views)
# flask의 create_app - Flask Application Factory
# debug / 
def create_app(debug=False):
	print('----------create_app----------')	
	app = Flask(__name__, template_folder='templates')
	app.secret_key = 'secretkey'
 
	# Blueprint views를 app에 등록
	app.register_blueprint(main_views.bp)

	# socketio.init_app(app) 추가

	return app

app_flask/project/views/main_views.py
# myproject/sesac/views/post_views.py
from flask import url_for, request, redirect, Blueprint, render_template
from project.conn.db import db

import os

bp = Blueprint('main_views', __name__, url_prefix='/')

path_data = '../data'


@bp.route('/')
def main():
    return render_template("pages/main.html")
    # return redirect(url_for('main_views.upload'))


@bp.route('/mypage')
def mypage():
    return render_template("pages/mypage.html")
    # return redirect(url_for('main_views.upload'))


@bp.route('/check')
def check():
    return render_template("pages/check.html")
    # return redirect(url_for('main_views.upload'))


@bp.route('/upload', methods=['GET', 'POST'])
def upload():
    path_input = '../db/data/input/'
    file_list = os.listdir(path_input)
    file_list = [file for file in file_list if not file.endswith(".md")]
    file_dict = {file: path_input+file for file in file_list}

    if request.method == 'POST':
        # print('file 저장')
        print(os.getcwd())
        f = request.files['file']

        path = path_input + f.filename
        f.save(path)

        return render_template("pages/file_upload_form.html")
        # return render_template("pages/file_upload_form.html", file_dict=file_dict)
    else:
        return render_template("pages/file_upload_form.html")
        # return render_template("pages/file_upload_form.html", file_dict=file_dict)


@bp.route('/success', methods=['POST'])
def success():
    if request.method == 'POST':
        return render_template("pages/success.html")

app_flask/project/templates/pages/dd.html
<head>
  <style>
    body {
      margin: 0;
    }
  </style>

  <script src="//unpkg.com/3d-force-graph"></script>
  <!--<script src="../../dist/3d-force-graph.js"></script>-->
</head>

<body>
  <div id="3d-graph"></div>

  <script>
    // Random tree
    const N = 300;
    const gData = {
      nodes: [...Array(N).keys()].map((i) => ({ id: i })),
      links: [...Array(N).keys()]
        .filter((id) => id)
        .map((id) => ({
          source: id,
          target: Math.round(Math.random() * (id - 1)),
        })),
    };

    const Graph = ForceGraph3D()(document.getElementById("3d-graph")).graphData(
      gData
    );
  </script>
</body>

app_flask/project/templates/pages/file_upload_form.html
<html>
  <head>
    <title>upload</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='css/upload.css') }}"
    />
  </head>
  <body>
    <h1>Document File Uploader</h1>
    <!-- <input
      type="file"
      id="fileUpload"
      accept=".doc,.docx,.pdf,.pptx"
      multiple
    />
    <button onclick="uploadFile()">Upload</button>
    <div id="fileList"></div> -->

    <button type="button" class="btn btn-primary" id="btnAppend">추가</button>
    <form action="/upload" method="post" enctype="multipart/form-data">
      <input
        type="file"
        id="upload"
        name="file"
        accept=".doc, .docx, .pdf, .pptx"
        multiple
      />
      <input
        type="submit"
        value="Upload"
        onclick="uploadFile()"
        id="btnUpload"
      />
    </form>
    <div id="fileList"></div>
    <ul id="file-list"></ul>

    <a href="{{url_for('main_views.main')}}">홈으로 가기</a>
  </body>
  <script src="{{ url_for('static', filename='js/upload_script.js') }}"></script>
</html>

app_flask/project/templates/pages/list.html
<table>
  <tr class="text-center table-dark">
    <th>번호</th>
    <th style="width: 50%">제목</th>
  </tr>
  {% for question in question_list.item %}
  <tr class="text-center">
    <td>{{ question.id }}</td>
    <!-- 글쓴이 추가 -->
    <td>{{ question.title }}</td>
  </tr>
  {% endfor %}
</table>

<ul class="pagination justify-content-center">
  <!-- 페이지번호 -->
  {% for page_num in question_list.max_page %} {% if page_num ==
  question_list.page %}
  <li class="page-item active" aria-current="page">
    <a class="page-link" href="javascript:void(0)">{{ page_num }}</a>
  </li>
  {% elif -5 < page_num - question_list.page < 5 %}
  <li class="page-item">
    <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
  </li>
  {% endif %} {% endfor %}
</ul>

app_flask/project/templates/pages/main.html
<html>
  <head>
    <title>Item Details</title>
  </head>
  <body>
    <h1>hello</h1>

    <div>
      <button type="button" class="btn btn-primary" id="search_btn">
        검색
      </button>
      <div id="result">ddd</div>
      <div id="fastapi_res">ddd</div>
    </div>
    <div>
      <a href="{{url_for('main_views.upload')}}">업로드 하러가기</a>
    </div>
    <div>
      <button type="button" class="btn btn-primary" id="doc2vec_btn">
        검색
      </button>
      <div id="result">ddd</div>
      <div id="fastapi_res">ddd</div>
    </div>
    <script src="{{ url_for('static', filename='js/main_script.js') }}"></script>
  </body>
</html>

app_flask/project/templates/pages/mypage.html
<html>
  <head>
    <title>Item Details</title>
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/mypage.css') }}"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Inter&display=swap"
      rel="stylesheet"
    />
  </head>
  <body>
    <div class="e141_2">
      <div class="e141_3">
        <div class="e141_4"></div>
        <div class="e141_5">
          <div class="e141_131">
            <div class="e141_132">
              <div class="e141_133"></div>
            </div>
            <div class="e141_134">
              <span class="e141_135">Document</span>
              <div class="e141_136"></div>
            </div>
          </div>
          <div class="e141_137">
            <div class="e141_138">
              <div class="e158_382"></div>
            </div>
            <div class="e141_140">
              <span class="e141_141">DB</span>
              <div class="e141_142"></div>
            </div>
          </div>
          <div class="e158_372">
            <div class="e158_373">
              <div class="e158_379"></div>
            </div>
            <div class="e158_375">
              <span class="e158_376">Report</span>
              <div class="e158_377"></div>
            </div>
          </div>
          <div class="e141_24">
            <div class="e141_25">
              <div class="e141_26"></div>
            </div>
            <div class="e141_27">
              <span class="e141_28">Setting</span>
              <div class="e141_29"></div>
            </div>
          </div>
          <div class="e141_12">
            <div class="e141_13">
              <div class="e141_14"></div>
            </div>
            <div class="e141_15">
              <span class="e141_16">Logout</span>
              <div class="e141_17"></div>
            </div>
          </div>
        </div>
      </div>
      <div class="e141_30">
        <div class="e141_31">
          <div class="e141_32">
            <span class="e141_33">사용자 님</span>
            <div class="e141_34"></div>
          </div>
          <div class="e141_35"></div>
        </div>
        <div class="e141_36">
          <div class="e141_37">
            <div class="e148_2120"></div>
            <span class="e141_40">Plagiarism Test</span>
          </div>
          <div class="e148_2044">
            <div class="e148_2118"></div>
            <span class="e148_2047">Upload</span>
          </div>
          <div class="e148_2048">
            <div class="e148_2116"></div>
            <span class="e148_2051">Delete</span>
          </div>
          <div class="e148_2036">
            <div class="e148_2038"></div>
            <span class="e148_2039">Filtrar</span>
          </div>
          <div class="e148_2035">
            <div class="e148_2040">
              <div class="e148_2042"></div>
              <span class="e148_2043">Search for a file name or extension</span>
            </div>
          </div>
        </div>
        <div class="e141_45">
          <div class="e141_46">
            <div class="e141_49">
              <div class="e141_50">
                <div class="e141_322">
                  <div class="e141_323"></div>
                  <div class="e141_324"></div>
                  <div class="e141_325"></div>
                  <div class="e141_326"></div>
                  <div class="e141_327">
                    <div class="e141_328"></div>
                  </div>
                  <div class="e141_329"></div>
                </div>
                <div class="e141_330">
                  <span class="e141_51">hello.pptx</span
                  ><span class="e141_52">23.03.01. 19:00</span>
                </div>
                <div class="e141_54">
                  <div class="e141_765"></div>
                  <span class="e141_55">Done</span>
                </div>
              </div>
            </div>
          </div>
          <div class="e141_385">
            <div class="e141_386">
              <div class="e141_387">
                <div class="e141_589">
                  <div class="e141_590">
                    <div class="e141_591">
                      <div class="e141_592"></div>
                      <div class="e141_593"></div>
                      <div class="e141_594"></div>
                      <div class="e141_595"></div>
                      <div class="e141_596"></div>
                      <div class="e141_597"></div>
                      <div class="e141_598"></div>
                      <div class="e141_599"></div>
                      <div class="e141_600"></div>
                      <div class="e141_601"></div>
                      <div class="e141_602">
                        <div class="e141_603"></div>
                        <div class="e141_604"></div>
                        <div class="e141_605"></div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="e141_396">
                  <span class="e141_397">hello.pdf</span
                  ><span class="e141_398">23.03.01. 19:00</span>
                </div>
                <div class="e141_766">
                  <div class="e141_767"></div>
                  <span class="e141_768">Done</span>
                </div>
              </div>
            </div>
          </div>
          <div class="e141_606">
            <div class="e141_607">
              <div class="e141_608">
                <div class="e141_609">
                  <div class="e141_610">
                    <div class="e141_611">
                      <div class="e141_612"></div>
                      <div class="e141_613"></div>
                      <div class="e141_614"></div>
                      <div class="e141_615"></div>
                      <div class="e141_616"></div>
                      <div class="e141_617"></div>
                      <div class="e141_618"></div>
                      <div class="e141_619"></div>
                      <div class="e141_620"></div>
                      <div class="e141_621"></div>
                      <div class="e141_622">
                        <div class="e141_623"></div>
                        <div class="e141_624"></div>
                        <div class="e141_625"></div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="e141_626">
                  <span class="e141_627">hello.pdf</span
                  ><span class="e141_628">23.03.01. 19:00</span>
                </div>
                <div class="e141_772">
                  <div class="e141_773"></div>
                  <span class="e141_774">In process</span>
                </div>
              </div>
            </div>
          </div>
          <div class="e141_656">
            <div class="e141_657">
              <div class="e141_658">
                <div class="e141_756">
                  <div class="e141_757"></div>
                  <div class="e141_758"></div>
                  <div class="e141_759"></div>
                  <div class="e141_760"></div>
                  <div class="e141_761"></div>
                  <div class="e141_762">
                    <div class="e141_763"></div>
                  </div>
                  <div class="e141_764"></div>
                </div>
                <div class="e141_676">
                  <span class="e141_677">hello.docx</span
                  ><span class="e141_678">23.03.01. 19:00</span>
                </div>
                <div class="e141_769">
                  <div class="e141_770"></div>
                  <span class="e141_771">Not Started</span>
                </div>
              </div>
            </div>
          </div>
          <div class="e141_731">
            <div class="e141_732">
              <div class="e141_733">
                <div class="e141_734">
                  <div class="e141_735">
                    <div class="e141_736">
                      <div class="e141_737"></div>
                      <div class="e141_738"></div>
                      <div class="e141_739"></div>
                      <div class="e141_740"></div>
                      <div class="e141_741"></div>
                      <div class="e141_742"></div>
                      <div class="e141_743"></div>
                      <div class="e141_744"></div>
                      <div class="e141_745"></div>
                      <div class="e141_746"></div>
                      <div class="e141_747">
                        <div class="e141_748"></div>
                        <div class="e141_749"></div>
                        <div class="e141_750"></div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="e141_751">
                  <span class="e141_752">hello.pptx</span
                  ><span class="e141_753">23.03.01. 19:00</span>
                </div>
                <div class="e141_775">
                  <div class="e141_776"></div>
                  <span class="e141_777">Not Started</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <script src="{{ url_for('static', filename='js/main_script.js') }}"></script>
  </body>
</html>

app_flask/project/templates/pages/success.html
<html>
  <head>
    <title>success</title>
  </head>
  <body>
    <p><button onclick="myFunction({{res}})">Click Me For Noun</button></p>

    <div id="myDIV"></div>
    <script>
      function myFunction(text) {
        var x = document.getElementById("myDIV");
        if (x.innerHTML === "") {
          x.innerHTML = text.noun;
        } else {
          x.innerHTML = "";
        }
      }
    </script>

    <p>File uploaded successfully</p>
    <p>File Name: {{name}}</p>
  </body>
</html>